config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :my_threads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :my_thread
end

app/models/my_thread.rb
class MyThread < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:my_thread_id, :content, :string)
    end
end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread, only: [:show, :edit, :update, :destroy]

  # GET /my_threads
  # GET /my_threads.json
  def index
    @my_threads = MyThread.all
  end

  # GET /my_threads/1
  # GET /my_threads/1.json
  def show
  end

  # GET /my_threads/new
  def new
    @my_thread = MyThread.new
  end

  # GET /my_threads/1/edit
  def edit
  end

  # POST /my_threads
  # POST /my_threads.json
  def create
    @my_thread = MyThread.new(my_thread_params)

    respond_to do |format|
      if @my_thread.save
        format.html { redirect_to @my_thread, notice: 'My thread was successfully created.' }
        format.json { render :show, status: :created, location: @my_thread }
      else
        format.html { render :new }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_threads/1
  # PATCH/PUT /my_threads/1.json
  def update
    respond_to do |format|
      if @my_thread.update(my_thread_params)
        format.html { redirect_to @my_thread, notice: 'My thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_thread }
      else
        format.html { render :edit }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_threads/1
  # DELETE /my_threads/1.json
  def destroy
    @my_thread.destroy
    respond_to do |format|
      format.html { redirect_to my_threads_url, notice: 'My thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_thread
      @my_thread = MyThread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_thread_params
      params.require(:my_thread).permit(:title, :string)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :my_thread_id %>
    <%= form.text_field :my_thread_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>My thread</th>
      <th>Content</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.my_thread %></td>
        <td><%= comment.content %></td>
        <td><%= comment.string %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My thread:</strong>
  <%= @comment.my_thread %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>String:</strong>
  <%= @comment.string %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_threads/_form.html.erb
<%= form_with(model: my_thread, local: true) do |form| %>
  <% if my_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_thread.errors.count, "error") %> prohibited this my_thread from being saved:</h2>

      <ul>
      <% my_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_threads/edit.html.erb
<h1>Editing My Thread</h1>

<%= render 'form', my_thread: @my_thread %>

<%= link_to 'Show', @my_thread %> |
<%= link_to 'Back', my_threads_path %>

app/views/my_threads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Threads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_threads.each do |my_thread| %>
      <tr>
        <td><%= my_thread.title %></td>
        <td><%= my_thread.string %></td>
        <td><%= link_to 'Show', my_thread %></td>
        <td><%= link_to 'Edit', edit_my_thread_path(my_thread) %></td>
        <td><%= link_to 'Destroy', my_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Thread', new_my_thread_path %>

app/views/my_threads/new.html.erb
<h1>New My Thread</h1>

<%= render 'form', my_thread: @my_thread %>

<%= link_to 'Back', my_threads_path %>

app/views/my_threads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @my_thread.title %>
</p>

<p>
  <strong>String:</strong>
  <%= @my_thread.string %>
</p>

<%= link_to 'Edit', edit_my_thread_path(@my_thread) %> |
<%= link_to 'Back', my_threads_path %>